config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :stocks
  resources :products
  resources :sizes
  resources :colors
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #root "messages#random_message"
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  },
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  
  devise_scope :user do
    get 'confirmation/resend', to: 'users/confirmations#resend', as: 'resend_confirmation'
    post 'resetPassword', to: 'users/passwords#create'
  end

  namespace :api do
    namespace :v1 do
      resources :categories, only: [:index]
      resources :products
    end
  end
end

app/models/adress.rb
class Adress < ApplicationRecord
  validates :street, presence: true
  validates :number, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :zipcode, presence: false
  has_many :user_addresses
  has_many :users, through: :user_addresses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/color.rb
class Color < ApplicationRecord
    has_many :stocks
    has_many :products, through: :stocks
      # Attributes
  attribute :name, :string
  attribute :code, :string

  # Validations
  validates :name, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :code, presence: true, uniqueness: true, length: { maximum: 7 },
  format: { with: /\A#[0-9A-Fa-f]{6}\z/ }
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
  belongs_to :color
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :stocks
  has_many :images
  has_many :colors, through: :stocks
  has_many :sizes, through: :stocks
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/size.rb
class Size < ApplicationRecord
    has_many :stocks
    has_many :products, through: :stocks
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :size
  belongs_to :color
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable, :confirmable, :registerable, :recoverable, :validatable, :jwt_authenticatable,
         jwt_revocation_strategy: self
  has_many :user_addresses
  has_many :addresses, through: :user_addresses
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
  belongs_to :address
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show; end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit; end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:name, :product_id, :default, :color_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :default, style: "display: block" %>
    <%= form.check_box :default %>
  </div>

  <div>
    <%= form.label :color_id, style: "display: block" %>
    <%= form.text_field :color_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Name:</strong>
    <%= image.name %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= image.product_id %>
  </p>

  <p>
    <strong>Default:</strong>
    <%= image.default %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= image.color_id %>
  </p>

</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Show this image", @image %> |
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Images</h1>

<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
    <p>
      <%= link_to "Show this image", image %>
    </p>
  <% end %>
</div>

<%= link_to "New image", new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render "form", image: @image %>

<br>

<div>
  <%= link_to "Back to images", images_path %>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>